- hosts: localhost
  become: yes
  vars:
    # source_key: "./.ssh/id_rsa"
    # dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
    # personal: "{{ lookup('env', 'HOME') }}/personal"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - include: tasks/zsh-setup.yml
    # - include: tasks/sdkman-setup.yml
    - include: tasks/nvim-setup.yml
    - include: tasks/tmux-setup.yml
    - include: tasks/dotfiles.yml

