- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  become_user: eox
  ansible.builtin.git:
    repo: 'https://github.com/safstromo/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  become_user: eox
  shell: cd $HOME/.dotfiles && chmod +x ubuntu && chmod +x install && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
