- name: Installing stow
  become: true
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  become_user: eox
  ansible.builtin.git:
    repo: 'https://github.com/safstromo/.dotfiles.git'
    dest: /home/eox/.dotfiles
    recursive: yes
    update: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd /home/eox/.dotfiles && chmod +x ubuntu && chmod +x install && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
