- name: Add Neovim PPA repository
  become: true
  apt_repository:
    repo: ppa:neovim-ppa/unstable
  tags:
    - install
    - dotfiles

- name: Update package cache
  become: true
  apt:
    update_cache: yes
  tags:
    - install
    - dotfiles

- name: Install Neovim
  apt:
    name: neovim
    state: present
  tags:
    - install
    - dotfiles

- name: Check Neovim version
  become: true
  command: nvim --version | head -1 | awk '{print $2}' | cut -c1-4
  register: neovim_version
  changed_when: false
  failed_when: false
  tags:
    - install
    - dotfiles

- name: Clone NvChad repository
  become_user: eox
  git:
    repo: https://github.com/NvChad/NvChad.git
    dest: /home/eox/.config/nvim
    depth: 1
  register: nvchad_repo
  tags:
    - install
    - dotfiles

- name: Install Ripgrep (optional for Telescope)
  become: true
  apt:
    name: ripgrep
    state: present
  when: nvchad_repo.changed
  tags:
    - install
    - dotfiles
