---
- name: Install Neovim and set up NvChad
  gather_facts: yes
  become: yes
  tags:
    - install
    - dotfiles
  tasks:
    - name: Check Neovim version
      command: nvim --version | head -1 | awk '{print $2}' | cut -c1-4
      register: neovim_version
      changed_when: false
      failed_when: false

    - name: Clone Neovim repository if needed
      git:
        repo: https://github.com/neovim/neovim.git
        dest: /tmp/neovim
        version: "v0.9.0"  # Replace with the version you want to install
      when: neovim_version.stdout != "0.9."

    - name: Build and install Neovim
      shell: |
        cd /tmp/neovim
        make CMAKE_BUILD_TYPE=RelWithDebInfo
        sudo make install
      when: neovim_version.stdout != "0.9."

    - name: Clone NvChad repository
      git:
        repo: https://github.com/NvChad/NvChad.git
        dest: ~/.config/nvim
        depth: 1
      register: nvchad_repo

    - name: Install Ripgrep (optional for Telescope)
      apt:
        name: ripgrep
        state: present
      when: nvchad_repo.changed

