- name: Download SDKMAN! Installer
  become_user: eox
  ansible.builtin.get_url:
    url: https://get.sdkman.io
    dest: /tmp/sdkman_installer.sh
  register: sdkman_installer

- name: Run SDKMAN! Installer
  become_user: eox
  ansible.builtin.shell: "bash /tmp/sdkman_installer.sh"
  environment:
    HOME: "{{ lookup('env', 'HOME') }}"
  when: sdkman_installer.failed == false

- name: Load SDKMAN! into the shell
  become_user: eox
  ansible.builtin.shell: source "$HOME/.sdkman/bin/sdkman-init.sh"
  environment:
    HOME: "{{ lookup('env', 'HOME') }}"
  when: sdkman_installer is defined and sdkman_installer.failed == false

- name: Install Java 20.0.2-tem
  become_user: eox
  ansible.builtin.shell: "sdk install java 20.0.2-tem"
  when: sdkman_installer.failed == false

- name: Install Java 17.0.8-tem
  become_user: eox
  ansible.builtin.shell: "sdk install java 17.0.8-tem"
  when: sdkman_installer.failed == false

- name: Install quarkus
  become_user: eox
  ansible.builtin.shell: "sdk install quarkus"
  when: sdkman_installer.failed == false

- name: Clean up SDKMAN! installer
  ansible.builtin.file:
    path: /tmp/sdkman_installer.sh
    state: absent

