- name: Install Tmux
  become: true
  apt:
    name: tmux
    state: present
  tags:
    - install
    - tmux

- name: Clone TPM (Tmux Plugin Manager) repository
  become_user: eox
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: /home/eox/.tmux/plugins/tpm
    update: yes # Update if the repository already exists
  tags:
    - install
    - tmux
    - tpm

# - name: Set GNOME Terminal to run Tmux on startup
#   ansible.builtin.command: >
#     gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gsettings get org.gnome.Terminal.ProfilesList default | awk -F "'" '{print $2}')/ custom-command "tmux"
#   tags:
#     - tmux
