- name: Install Tmux and Tmux Plugin Manager (TPM)
  hosts: localhost  # You can change the target host if needed
  become: yes      # Run with elevated privileges (sudo)
  tasks:
    - name: Install Tmux
      apt:
        name: tmux
        state: present
      tags:
        - install
        - tmux

    - name: Clone TPM (Tmux Plugin Manager) repository
      git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: ~/.tmux/plugins/tpm
        update: yes  # Update if the repository already exists
      tags:
        - install
        - tmux
        - tpm

