- name: Install ZSH and Dependencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - curl  # Install curl as a dependency
    - unzip
    - fontconfig
    - zip
    - npm
    - python3-pip
    - nodejs
  tags: &tags_for_zsh_tasks ["install", "dotfiles", "zsh"]

- name: Change shell to Zsh
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Check if Oh-My-Zsh is installed
  stat:
    path: /home/eox/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks


- name: Install Oh-My-Zsh for eox
  become_user: eox
  shell: >
    curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > /home/eox/.oh-my-installer &&
    chmod +x /home/eox/.oh-my-installer &&
    /home/eox/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False


- name: Download JetBrains Mono Nerd Font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
    dest: /tmp/JetBrainsMono.zip
  tags: *tags_for_zsh_tasks

- name: Create the directory for JetBrains Mono Nerd Font
  ansible.builtin.file:
    path: /usr/local/share/fonts
    state: directory
  tags: *tags_for_zsh_tasks

- name: Extract JetBrains Mono Nerd Font
  ansible.builtin.unarchive:
    src: /tmp/JetBrainsMono.zip
    dest: /usr/local/share/fonts
  tags: *tags_for_zsh_tasks

- name: Update Font Cache
  ansible.builtin.command: fc-cache -f -v
  tags: *tags_for_zsh_tasks

# - name: Set Terminal Font (GNOME Terminal)
#   ansible.builtin.command:
#     cmd: gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gsettings get org.gnome.Terminal.ProfilesList default | awk -F "'" '{print $2}')/ font 'JetBrains Mono Nerd Font 12'
#   tags: *tags_for_zsh_tasks

- name: Install Starship for eox
  become_user: eox
  shell: |
    curl -fsSL https://starship.rs/install.sh -o /home/eox/starship_install.sh &&
    chmod +x /home/eox/starship_install.sh &&
    /home/eox/starship_install.sh -y
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions for eox
  become_user: eox
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "/home/eox/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks


