- name: Install ZSH and Dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - zsh
    - curl  # Install curl as a dependency
  tags: &tags_for_zsh_tasks ["install", "dotfiles", "zsh"]

- name: Change shell to Zsh
  shell: chsh -s $(which zsh)
  tags: *tags_for_zsh_tasks

- name: Check if Oh-My-Zsh is installed
  stat:
    path: /home/eox/.oh-my-zsh
  register: oh_my_stats
  tags: *tags_for_zsh_tasks

- name: Install Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh > ~/.oh-my-installer && chmod +x ~/.oh-my-installer && ~/.oh-my-installer
  tags: *tags_for_zsh_tasks
  when: oh_my_stats.stat.exists == False
  become_user: eox

- name: Download JetBrains Mono Nerd Font
  ansible.builtin.get_url:
    url: https://github.com/ryanoasis/nerd-fonts/releases/download/v3.0.2/JetBrainsMono.zip
    dest: /tmp/JetBrainsMono.zip
  tags: *tags_for_zsh_tasks

- name: Extract JetBrains Mono Nerd Font
  ansible.builtin.unarchive:
    src: /tmp/JetBrainsMono.zip
    dest: /usr/local/share/fonts/JetBrainsMono
  tags: *tags_for_zsh_tasks

- name: Update Font Cache
  ansible.builtin.command: fc-cache -f -v
  tags: *tags_for_zsh_tasks

- name: Set Terminal Font (GNOME Terminal)
  ansible.builtin.command: >
    gsettings set org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$(gsettings get org.gnome.Terminal.ProfilesList default | awk -F "'" '{print $2}')/ font 'JetBrains Mono Nerd Font 12'
  tags: *tags_for_zsh_tasks

- name: Install Starship
  shell: curl -fsSL https://starship.rs/install.sh -o starship_install.sh && chmod +x ./starship_install.sh && ./starship_install.sh -y
  tags: *tags_for_zsh_tasks

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: *tags_for_zsh_tasks

